use_frameworks!

platform :ios, '8.0'

target 'DDCameraViewController_Example' do
  pod 'DDCameraViewController', :path => '../'

  target 'DDCameraViewController_Tests' do
    inherit! :search_paths

    
  end
end
