use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'DDCameraViewController_Example' do
  pod 'DDCameraViewController', :path => '../'
end

target 'DDCameraViewController_Tests' do
    pod 'DDCameraViewController', :path => '../'
    pod 'OCMock', '~> 3.1.2'
end

