# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/DDCameraViewController.xcworkspace -scheme DDCameraViewController-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone X' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
